# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for runs with userManagedDependencies=False.

# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.8.10

- pip:
  - ''
  - click
  - Sphinx
  - coverage
  - awscli
  - flake8
  - python-dotenv>=0.5.1
  - numpy
  - torchmetrics
  - pytorch-lightning
  - wandb
  - joblib
  - pathlib2
  - -e git+https://github.com/petergroth/enzyme_graph_classification@main#egg=src
  - torch==1.8.1
  - torch-scatter
  - torch-sparse
  - torch-cluster
  - torch-spline-conv
  - torch-geometric
  - -f https://pytorch-geometric.com/whl/torch-1.8.1+cpu.html
- pip==21.1.2
channels:
- anaconda
- conda-forge
