name: "Run flake8"

on:
  push:
    branches: [ main, pmg_local, jv_local ]
  pull_request:
    branches: [ main, pmg_local, jv_local ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Use flake8
      run: |
        pip install flake8
        flake8 .
